[package]
# Package names are always "SCOPE/NAME"
name = "creepersaur/quark"

description = "Reactive UI library"
version = "0.0.8"
license = "MIT"
authors = ["creepersaur"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"